export enum UserActions {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
}

export enum LibraryActions {
  SELECT_CATEGORY = 'SELECT_CATEGORY',
  SELECT_BOOK = 'SELECT_BOOK',
  BORROW_SUCCESS = 'BORROW_SUCCESS',
  BORROW_FAILURE = 'BORROW_FAILURE',
  RETURN_SUCCESS = 'RETURN_SUCCESS',
  RETURN_FAILURE = 'RETURN_FAILURE',
  RESET_ERRORS = 'RESET_ERRORS',
}
